#!/bin/bash
set -euo pipefail

# Build a combined Free+Pro binary of SilbercueSwift.
# Temporarily injects the Pro module as a dependency, builds release, then restores.
#
# Usage:
#   ./scripts/build-combined.sh [/path/to/SilbercueSwiftPro]
#
# Default Pro path: ../../SilbercueSwiftPro (relative to SilbercueSwiftMCP/)

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
MCP_DIR="$(dirname "$SCRIPT_DIR")"
PACKAGE="$MCP_DIR/Package.swift"
BACKUP="$MCP_DIR/Package.swift.bak"

# Pro path: argument or default (relative to MCP_DIR)
PRO_PATH="${1:-../../SilbercueSwiftPro}"

# Convert to absolute if relative
if [[ "$PRO_PATH" != /* ]]; then
    PRO_PATH="$(cd "$MCP_DIR" && cd "$PRO_PATH" 2>/dev/null && pwd)" || {
        echo "ERROR: Pro repo not found at $1 (resolved from $MCP_DIR)" >&2
        exit 1
    }
fi

# Verify Pro repo
if [[ ! -f "$PRO_PATH/Package.swift" ]]; then
    echo "ERROR: No Package.swift found at $PRO_PATH" >&2
    exit 1
fi

echo "=== SilbercueSwift Combined Build ==="
echo "Free: $MCP_DIR"
echo "Pro:  $PRO_PATH"

# Backup original Package.swift
cp "$PACKAGE" "$BACKUP"

# Restore on exit (success or failure)
cleanup() {
    if [[ -f "$BACKUP" ]]; then
        mv "$BACKUP" "$PACKAGE"
    fi
}
trap cleanup EXIT

# Generate combined Package.swift
cat > "$PACKAGE" << SWIFT
// swift-tools-version: 6.0
// GENERATED by build-combined.sh — do not commit
import PackageDescription

let package = Package(
    name: "SilbercueSwift",
    platforms: [.macOS(.v13)],
    products: [
        .library(name: "SilbercueSwiftCore", targets: ["SilbercueSwiftCore"]),
    ],
    dependencies: [
        .package(url: "https://github.com/modelcontextprotocol/swift-sdk.git", from: "0.11.0"),
        .package(url: "https://github.com/apple/swift-log.git", from: "1.0.0"),
        .package(path: "$PRO_PATH"),
    ],
    targets: [
        .target(
            name: "SilbercueSwiftCore",
            dependencies: [
                .product(name: "MCP", package: "swift-sdk"),
                .product(name: "Logging", package: "swift-log"),
            ]
        ),
        .executableTarget(
            name: "SilbercueSwift",
            dependencies: [
                "SilbercueSwiftCore",
                .product(name: "SilbercueSwiftPro", package: "SilbercueSwiftPro"),
                .product(name: "MCP", package: "swift-sdk"),
                .product(name: "Logging", package: "swift-log"),
            ]
        ),
        .testTarget(
            name: "SmartContextTests",
            dependencies: ["SilbercueSwiftCore"]
        ),
    ]
)
SWIFT

echo "Building release..."
cd "$MCP_DIR"
swift build -c release 2>&1

BINARY="$MCP_DIR/.build/release/SilbercueSwift"
if [[ -f "$BINARY" ]]; then
    SIZE=$(du -h "$BINARY" | cut -f1 | xargs)
    echo ""
    echo "=== Build successful ==="
    echo "Binary: $BINARY ($SIZE)"
    echo ""
    # Quick sanity check
    "$BINARY" version 2>&1 || true
else
    echo "ERROR: Binary not found at $BINARY" >&2
    exit 1
fi
